#!/bin/sh

PATH="$PATH:/root/omhacks"
STORAGEDIR="$PM_UTILS_RUNDIR/$STASHNAME/storage"

suspend() {
	om-led --swap gta02-power:blue 255 > "$STORAGEDIR/saved-blueled"
}

resume() {
	if read val < "$STORAGEDIR/saved-blueled"
	then
		om-led gta02-power:blue $val
	else
		om-led gta02-power:blue 0
	fi
}

case "$1" in
	hibernate|suspend)
		suspend
	;;
	thaw|resume)
		resume
	;;
	*) exit $NA
	;;
esac

exit 0
